#!/usr/bin/env bash
set -euo pipefail

NEXT_TELEMETRY_DISABLED="1"

AUTH_SECRET=$(openssl rand -hex 64)
read -p "Enter your AUTH_DISCORD_ID: " AUTH_DISCORD_ID
read -p "Enter your AUTH_DISCORD_SECRET: " AUTH_DISCORD_SECRET
AUTH_TRUST_HOST="1"
AUTH_URL="http://localhost:3000"

POSTGRES_USER="postgres"
POSTGRES_PASSWORD=$(openssl rand -hex 64)
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"
POSTGRES_DB="web"
POSTGRES_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB"

MINIO_USER="minioadmin"
MINIO_PASSWORD=$(openssl rand -hex 64)
MINIO_ENDPOINT="localhost"
MINIO_PORT="9000"
MINIO_USE_SSL="0"

cat <<EOF > .env
NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED
AUTH_SECRET=$AUTH_SECRET
AUTH_DISCORD_ID=$AUTH_DISCORD_ID
AUTH_DISCORD_SECRET=$AUTH_DISCORD_SECRET
AUTH_TRUST_HOST=$AUTH_TRUST_HOST
AUTH_URL=$AUTH_URL
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_DB=$POSTGRES_DB
POSTGRES_URL=$POSTGRES_URL
MINIO_USER=$MINIO_USER
MINIO_PASSWORD=$MINIO_PASSWORD
MINIO_ENDPOINT=$MINIO_ENDPOINT
MINIO_PORT=$MINIO_PORT
MINIO_USE_SSL=$MINIO_USE_SSL
EOF
