#!/usr/bin/env bash
set -euo pipefail

read -p "Enter your AUTH_DISCORD_ID: " AUTH_DISCORD_ID
read -p "Enter your AUTH_DISCORD_SECRET: " AUTH_DISCORD_SECRET

AUTH_SECRET=$(openssl rand -hex 64)

POSTGRES_USER="postgres"
POSTGRES_PASSWORD=$(openssl rand -hex 64)
POSTGRES_HOST="localhost"
POSTGRES_PORT="5432"
POSTGRES_DB="web"
POSTGRES_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB"


cat <<EOF > .env
AUTH_SECRET=$AUTH_SECRET
AUTH_DISCORD_ID=$AUTH_DISCORD_ID
AUTH_DISCORD_SECRET=$AUTH_DISCORD_SECRET
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_HOST=$POSTGRES_HOST
POSTGRES_PORT=$POSTGRES_PORT
POSTGRES_DB=$POSTGRES_DB
POSTGRES_URL=$POSTGRES_URL
EOF
